const Database = require('better-sqlite3');
const db = new Database('C:\\Users\\iamho\\AppData\\Roaming\\narenj-reconciliation\\narenj.db', {readonly:true});
const r = {};
r.bank_unmatched = db.prepare("SELECT count(*) as c FROM bank_transactions WHERE status='unmatched'").get();
r.bank_matched = db.prepare("SELECT count(*) as c FROM bank_transactions WHERE status='matched'").get();
r.bank_manual = db.prepare("SELECT count(*) as c FROM bank_transactions WHERE status='manual'").get();
r.bank_total = db.prepare("SELECT count(*) as c FROM bank_transactions").get();
r.acc_unmatched = db.prepare("SELECT count(*) as c FROM accounting_entries WHERE status='unmatched'").get();
r.acc_matched = db.prepare("SELECT count(*) as c FROM accounting_entries WHERE status='matched'").get();
r.acc_manual = db.prepare("SELECT count(*) as c FROM accounting_entries WHERE status='manual'").get();
r.acc_total = db.prepare("SELECT count(*) as c FROM accounting_entries").get();
r.pos_unmatched = db.prepare("SELECT count(*) as c FROM pos_transactions WHERE status='unmatched'").get();
r.pos_matched = db.prepare("SELECT count(*) as c FROM pos_transactions WHERE status='matched'").get();
r.pos_manual = db.prepare("SELECT count(*) as c FROM pos_transactions WHERE status='manual'").get();
r.pos_total = db.prepare("SELECT count(*) as c FROM pos_transactions").get();
r.links = db.prepare("SELECT layer, match_type, count(*) as c FROM reconciliation_links GROUP BY layer, match_type").all();
r.fee_agg = db.prepare("SELECT * FROM fee_aggregations").all();
console.log(JSON.stringify(r, null, 2));
db.close();
